import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import {
  financialYearOf,
  financialYearRange,
  type StatementLine,
  type TenantContext,
} from '@templeos/core';
import { Alert, cn, formatMoney } from '@templeos/ui';
import { PrintButton } from '@/components/print-button';
import { requireTenantContext } from '@/lib/session';
import { statementService } from '@/lib/services';

export const metadata: Metadata = { title: 'Statements' };

interface StatementPageProps {
  searchParams: Promise<{ fy?: string; from?: string; to?: string; view?: string }>;
}

type View = 'ie' | 'rnp' | 'bs';

const DATE = /^\d{4}-\d{2}-\d{2}$/;

function LineTable({
  lines,
  currency,
  leadRow,
  totalLabel,
  total,
  tailRow,
}: {
  lines: StatementLine[];
  currency: 'INR' | 'BDT' | 'USD' | 'GBP' | 'CAD' | 'AUD';
  leadRow?: { label: string; value: string };
  totalLabel: string;
  total: string;
  tailRow?: { label: string; value: string };
}) {
  return (
    <table className="w-full text-sm">
      <tbody>
        {leadRow ? (
          <tr className="border-b border-border/60 font-medium">
            <td className="py-1.5">{leadRow.label}</td>
            <td className="py-1.5 text-right tabular-nums">
              {formatMoney(leadRow.value, currency)}
            </td>
          </tr>
        ) : null}
        {lines.length === 0 && !leadRow && !tailRow ? (
          <tr>
            <td className="py-1.5 text-muted-foreground">None recorded</td>
            <td />
          </tr>
        ) : (
          lines.map((l) => (
            <tr key={l.label} className="border-b border-border/60">
              <td className="py-1.5">{l.label}</td>
              <td className="py-1.5 text-right tabular-nums">{formatMoney(l.total, currency)}</td>
            </tr>
          ))
        )}
        {tailRow ? (
          <tr className="border-b border-border/60 font-medium">
            <td className="py-1.5">{tailRow.label}</td>
            <td className="py-1.5 text-right tabular-nums">
              {formatMoney(tailRow.value, currency)}
            </td>
          </tr>
        ) : null}
      </tbody>
      <tfoot>
        <tr className="border-t-2 border-border font-semibold">
          <td className="py-2">{totalLabel}</td>
          <td className="py-2 text-right tabular-nums">{formatMoney(total, currency)}</td>
        </tr>
      </tfoot>
    </table>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div>
      <h3 className="mb-2 text-sm font-semibold tracking-wide text-muted-foreground uppercase">
        {title}
      </h3>
      {children}
    </div>
  );
}

async function IncomeExpenditure({
  ctx,
  range,
  orgName,
  periodLabel,
}: {
  ctx: TenantContext;
  range: { from: string; to: string };
  orgName: string;
  periodLabel: string;
}) {
  const result = await statementService().getStatement(ctx, range);
  if (!result.ok) return <Alert tone="error">{result.error.message}</Alert>;
  const s = result.value;
  const isDeficit = s.net.startsWith('-');
  const netDisplay = formatMoney(s.net.replace('-', ''), s.currency);

  return (
    <div className="mx-auto max-w-2xl rounded-xl border border-border bg-card p-8 shadow-card print:border-0 print:shadow-none">
      <div className="mb-6 text-center">
        <h2 className="text-lg font-semibold">{orgName}</h2>
        <p className="text-sm text-muted-foreground">Income &amp; Expenditure Statement</p>
        <p className="text-sm text-muted-foreground">{periodLabel}</p>
      </div>
      <div className="space-y-8">
        <Section title="Income">
          <LineTable
            lines={s.income}
            currency={s.currency}
            totalLabel="Total income"
            total={s.incomeTotal}
          />
        </Section>
        <Section title="Expenditure">
          <LineTable
            lines={s.expenditure}
            currency={s.currency}
            totalLabel="Total expenditure"
            total={s.expenditureTotal}
          />
        </Section>
        <div
          className={cn(
            'flex items-center justify-between rounded-lg border px-4 py-3 text-base font-semibold',
            isDeficit
              ? 'border-destructive/30 bg-destructive/5 text-destructive'
              : 'border-success/30 bg-success/5 text-success',
          )}
        >
          <span>{isDeficit ? 'Deficit for the period' : 'Surplus for the period'}</span>
          <span className="tabular-nums">{netDisplay}</span>
        </div>
      </div>
      <p className="mt-8 text-center text-xs text-muted-foreground">
        Generated by TempleOS · figures exclude voided entries
      </p>
    </div>
  );
}

async function ReceiptsAndPayments({
  ctx,
  range,
  orgName,
  periodLabel,
}: {
  ctx: TenantContext;
  range: { from: string; to: string };
  orgName: string;
  periodLabel: string;
}) {
  const result = await statementService().getReceiptsAndPayments(ctx, range);
  if (!result.ok) return <Alert tone="error">{result.error.message}</Alert>;
  const s = result.value;

  return (
    <div className="mx-auto max-w-2xl rounded-xl border border-border bg-card p-8 shadow-card print:border-0 print:shadow-none">
      <div className="mb-6 text-center">
        <h2 className="text-lg font-semibold">{orgName}</h2>
        <p className="text-sm text-muted-foreground">Receipts &amp; Payments Account</p>
        <p className="text-sm text-muted-foreground">{periodLabel}</p>
      </div>
      <div className="space-y-8">
        <Section title="Receipts">
          <LineTable
            lines={s.receipts}
            currency={s.currency}
            leadRow={{ label: 'Opening balance (cash & bank)', value: s.openingBalance }}
            totalLabel="Total"
            total={(Number(s.openingBalance) + Number(s.receiptsTotal)).toFixed(2)}
          />
        </Section>
        <Section title="Payments">
          <LineTable
            lines={s.payments}
            currency={s.currency}
            tailRow={{ label: 'Closing balance (cash & bank)', value: s.closingBalance }}
            totalLabel="Total"
            total={(Number(s.paymentsTotal) + Number(s.closingBalance)).toFixed(2)}
          />
        </Section>
      </div>
      <p className="mt-8 text-center text-xs text-muted-foreground">
        Opening balance rolls forward from account opening balances and prior cash movements ·
        excludes voided entries
      </p>
    </div>
  );
}

async function BalanceSheetView({
  ctx,
  orgName,
}: {
  ctx: TenantContext;
  orgName: string;
}) {
  const result = await statementService().getBalanceSheet(ctx);
  if (!result.ok) return <Alert tone="error">{result.error.message}</Alert>;
  const s = result.value;
  const liabilitiesAndFunds = (Number(s.liabilitiesTotal) + Number(s.fundsTotal)).toFixed(2);

  return (
    <div className="mx-auto max-w-3xl rounded-xl border border-border bg-card p-8 shadow-card print:border-0 print:shadow-none">
      <div className="mb-6 text-center">
        <h2 className="text-lg font-semibold">{orgName}</h2>
        <p className="text-sm text-muted-foreground">Statement of Financial Position</p>
        <p className="text-sm text-muted-foreground">As on {s.asOf}</p>
      </div>
      <div className="grid gap-8 md:grid-cols-2">
        <div className="space-y-6">
          <Section title="Funds">
            <LineTable
              lines={s.funds}
              currency={s.currency}
              totalLabel="Total funds"
              total={s.fundsTotal}
            />
          </Section>
          <Section title="Liabilities">
            <LineTable
              lines={s.liabilities}
              currency={s.currency}
              totalLabel="Total liabilities"
              total={s.liabilitiesTotal}
            />
          </Section>
          <div className="flex items-center justify-between border-t-2 border-border pt-2 text-sm font-semibold">
            <span>Funds &amp; liabilities</span>
            <span className="tabular-nums">{formatMoney(liabilitiesAndFunds, s.currency)}</span>
          </div>
        </div>
        <div className="space-y-6">
          <Section title="Assets">
            <LineTable
              lines={s.assets}
              currency={s.currency}
              totalLabel="Total assets"
              total={s.assetsTotal}
            />
          </Section>
          <div className="flex items-center justify-between border-t-2 border-border pt-2 text-sm font-semibold">
            <span>Total assets</span>
            <span className="tabular-nums">{formatMoney(s.assetsTotal, s.currency)}</span>
          </div>
        </div>
      </div>
      {s.memorandum.length > 0 ? (
        <div className="mt-8 rounded-lg border border-dashed border-border bg-muted/30 p-5">
          <h3 className="text-sm font-semibold">Memorandum</h3>
          <p className="mt-0.5 text-xs text-muted-foreground">
            Tracked in their own registers and shown for information — not included in the totals
            above, as they are not yet posted through the cash ledger.
          </p>
          <dl className="mt-3 space-y-1.5">
            {s.memorandum.map((l) => (
              <div key={l.label} className="flex items-center justify-between text-sm">
                <dt className="text-muted-foreground">{l.label}</dt>
                <dd className="tabular-nums">{formatMoney(l.total, s.currency)}</dd>
              </div>
            ))}
          </dl>
        </div>
      ) : null}
      <p className="mt-8 text-center text-xs text-muted-foreground">
        Derived from the ledger · the general fund is the balancing figure · excludes voided entries
      </p>
    </div>
  );
}

export default async function StatementPage({ searchParams }: StatementPageProps) {
  const params = await searchParams;
  const { ctx, membership } = await requireTenantContext('accounting');

  const view: View = params.view === 'rnp' ? 'rnp' : params.view === 'bs' ? 'bs' : 'ie';
  const isRnp = view === 'rnp';
  const isBs = view === 'bs';
  const currentFy = financialYearOf(new Date());
  const custom = DATE.test(params.from ?? '') && DATE.test(params.to ?? '');
  const fyStart = Number.isFinite(Number(params.fy)) && params.fy ? Number(params.fy) : currentFy;
  const range = custom
    ? { from: params.from!, to: params.to! }
    : { from: financialYearRange(fyStart).from, to: financialYearRange(fyStart).to };

  const fyOptions = Array.from({ length: 5 }, (_, i) => currentFy - i);
  const periodLabel = custom
    ? `${range.from} to ${range.to}`
    : financialYearRange(fyStart).label + ' (Apr–Mar)';
  const csvHref = isBs
    ? '/statements/balance-sheet.csv'
    : `/statements/${isRnp ? 'receipts-payments' : 'statement'}.csv?${new URLSearchParams(range).toString()}`;
  const fyQ = custom ? '' : `fy=${fyStart}`;
  const tab = (v: View, label: string) => {
    const active = view === v;
    const href = v === 'ie' ? `/statements${fyQ ? `?${fyQ}` : ''}` : `/statements?view=${v}${fyQ ? `&${fyQ}` : ''}`;
    return (
      <a
        href={href}
        className={cn(
          'rounded-md px-3 py-1.5 font-medium',
          active ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground',
        )}
      >
        {label}
      </a>
    );
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Financial statements</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            The year-end statements for your AGM, trustees and auditors.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <a
            href={csvHref}
            className="inline-flex h-9.5 items-center rounded-lg border border-input bg-card px-4 text-sm font-medium shadow-card transition-colors hover:bg-muted/60"
          >
            Export CSV
          </a>
          <PrintButton />
        </div>
      </div>

      {/* View toggle */}
      <div className="inline-flex flex-wrap rounded-lg border border-border bg-card p-0.5 text-sm print:hidden">
        {tab('ie', 'Income & Expenditure')}
        {tab('rnp', 'Receipts & Payments')}
        {tab('bs', 'Balance Sheet')}
      </div>

      {/* Period picker — the balance sheet is an as-on-today snapshot */}
      {isBs ? null : (
        <form action="/statements" className="flex flex-wrap items-end gap-3 print:hidden">
          {isRnp ? <input type="hidden" name="view" value="rnp" /> : null}
          <div className="space-y-1.5">
            <label htmlFor="fy" className="text-sm font-medium">
              Financial year
            </label>
            <select
              id="fy"
              name="fy"
              defaultValue={custom ? '' : String(fyStart)}
              className="h-9.5 rounded-lg border border-input bg-card px-3 text-sm"
            >
              {fyOptions.map((y) => (
                <option key={y} value={y}>
                  {y}–{y + 1}
                </option>
              ))}
            </select>
          </div>
          <button
            type="submit"
            className="inline-flex h-9.5 items-center rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-card hover:bg-primary/90"
          >
            View
          </button>
        </form>
      )}

      {isBs ? (
        <BalanceSheetView ctx={ctx} orgName={membership.organizationName} />
      ) : isRnp ? (
        <ReceiptsAndPayments
          ctx={ctx}
          range={range}
          orgName={membership.organizationName}
          periodLabel={periodLabel}
        />
      ) : (
        <IncomeExpenditure
          ctx={ctx}
          range={range}
          orgName={membership.organizationName}
          periodLabel={periodLabel}
        />
      )}
    </div>
  );
}
